# Generated by Django 3.1.5 on 2021-01-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=100)),
                ('transfer_address', models.CharField(max_length=100)),
                ('transfer_network_number', models.IntegerField()),
                ('validation_status', models.CharField(default='WAITING FOR VALIDATION', max_length=100)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
        ),
    ]
