# Generated by Django 3.1.5 on 2021-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasInfo',
            fields=[
                ('network', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price_limit', models.IntegerField()),
            ],
        ),
    ]
