# Generated by Django 3.1.5 on 2021-01-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=100)),
                ('fee_address', models.CharField(max_length=100)),
                ('fee_amount', models.DecimalField(decimal_places=0, max_digits=100)),
                ('tx_hash', models.CharField(max_length=100)),
                ('tx_error', models.TextField(default='')),
                ('status', models.CharField(default='WAITING FOR TRANSFER', max_length=50)),
                ('network', models.CharField(max_length=100)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
        ),
    ]
